name: Kubernetes Scan using kube-hunter
on:
  push:
  workflow_dispatch:
  
jobs:
  Kubernetes-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.2
      continue-on-error: true
    
    - name: Use Vulnerable kubernetes application
      continue-on-error: true
      run: |
         sudo apt install -y curl wget apt-transport-https
         wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
         sudo cp minikube-linux-amd64 /usr/local/bin/minikube
         sudo chmod +x /usr/local/bin/minikube
         minikube version
         curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl 
         chmod +x kubectl
         sudo mv kubectl /usr/local/bin/
         #kubectl version -o yaml
         minikube start --driver=docker
         minikube status
         kubectl cluster-info
         kubectl get nodes
         kubectl create deployment my-nginx --image=nginx
         kubectl get deployments.apps my-nginx
         kubectl get pods
         kubectl expose deployment my-nginx --name=my-nginx-svc --type=NodePort --port=80
         kubectl get svc my-nginx-svc
         minikube service my-nginx-svc --url http://192.168.49.2:31895
         #curl http://192.168.49.2:31895
         docker run -it --rm --network host aquasec/kube-hunter --interface
         
         
         
         
         
         
