name: Kubernetes Scan using kube-hunter
on:
  push:
  workflow_dispatch:
  
jobs:
  Kubernetes-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Use Vulnerable kubernetes application 
      run: |
         sudo apt install -y curl wget apt-transport-https
         wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
         sudo cp minikube-linux-amd64 /usr/local/bin/minikube
         sudo chmod +x /usr/local/bin/minikube
         minikube version
    
