name: Kubernetes Scan using kube-hunter
on:
 # push:
  workflow_dispatch:
  
jobs:
  Kubernetes-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.2
      continue-on-error: true 
    - name: Deploy to Kubernetes
     # You may pin to the exact commit or the version.
     # uses: Firehed/deploy-to-kubernetes-action@b651fe96d385988dd795880c81ddab4bca2b3228
      uses: Firehed/deploy-to-kubernetes-action@v0.3.0
      with:
       # The Kubernetes Namespace that the Deployment is in. If omitted, the `--namespace` flag is not used and the default Kubernetes behavior will apply.

       namespace:  default
       # The Deployment to update.
       deployment: my-nginx
       # The name of the Container in the Deployment that will have its image updated.
       container: nginx
       # The image to deploy.
       image: nginx
       # The token to use for the Github API.Normally you will use `secrets.GITHUB_TOKEN`.
       token: secrets.GITHUB_TOKEN
    
