name: Kubernetes Scan using kube-hunter
on:
  push:
  workflow_dispatch:
  
jobs:
  Kubernetes-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.2
      continue-on-error: true
    
    - name: Set up minikube
      continue-on-error: true
      run: |
         sudo apt install -y curl wget apt-transport-https
         wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
         sudo cp minikube-linux-amd64 /usr/local/bin/minikube
         sudo chmod +x /usr/local/bin/minikube
         minikube version
         curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl 
    - name: Setup kubectl
      continue-on-error: true
      run: |
         chmod +x kubectl
         sudo mv kubectl /usr/local/bin/
         #kubectl version -o yaml
         minikube start --driver=docker
         minikube status
         kubectl cluster-info
         kubectl get nodes
        
    - name: Deploy application
      continue-on-error: true
      run: |
         kubectl create deployment my-nginx --image=nginx
         kubectl get deployments.apps my-nginx
         kubectl get deployments.apps my-nginx
         kubectl get deployments.apps my-nginx
         kubectl get deployments.apps my-nginx
         kubectl get deployments.apps my-nginx
         kubectl get deployments.apps my-nginx
         kubectl get pods
         kubectl get pods
         kubectl get pods
         kubectl get pods
         kubectl get pods
         kubectl get pods
         export DEPLOY_STATUS=$(kubectl get deployments.apps my-nginx -o go-template --template '{{range .items}}{{.metadata.available}}{{"\n"}}{{end}}')
         echo $DEPLOY_STATUS
         #if($DEPLOY_STATUS==0)
         if $DEPLOY_STATUS==0; then kubectl get pods && POD_STATUS=$(kubectl get deployments.apps my-nginx -o go-template --template '{{range .items}}{{.metadata.available}}{{"\n"}}{{end}}') ; fi
         echo DEPLOY_STATUS
    - name: Expose application
      continue-on-error: true
      run: |
         
         kubectl expose deployment my-nginx --name=my-nginx-svc --type=NodePort --port=81
         kubectl get svc my-nginx-svc
         #minikube service my-nginx-svc --url 
         #curl http://192.168.49.2:31895
    - name: Run Kube-hunter
      continue-on-error: true
      # uses: actions/checkout@v2.4.2
      # with:
      #  Repository name with owner. For example, actions/checkout
      #  repository:  https://github.com/aquasecurity/kube-hunter.git
      run: |
        git clone https://github.com/aquasecurity/kube-hunter.git
        cd ./kube-hunter
        pip install -r requirements.txt
        python3 kube_hunter --interface
        python3 kube_hunter --pod
        
        
        
         
  
       
         
         
         
         
         
         
